### ISSUE TITLE
Strict Mode and Octals

### ISSUE THREAD

**Issue by kriskowal** [Gozala/test-commonjs#1]
The ban on octals in strict mode is now enforced by V8/Node:

test/0.0.10/package/lib/log.js:11
  , COLOR_RESET = '\033[m'

**Comment by Gozala** [comment]
But that's string no ?
Also is there any way I can test that ?

**Comment by kriskowal** [comment]
The error shows up in Node 0.4.0. I wasn't aware that the octal ban extended to strings either.

**Comment by Gozala** [comment]
Ok I'll remove strict mode at the moment and will try to investigate further.

**Comment by Gozala** [comment]
I have published into npm v0.0.11 that just removes "use strict", can you please try if that solves problem temporarily ? (I'm not on 0.4.0 yet and in the middle of something, that I really don't want to break :)

**Comment by kriskowal** [comment]
Works for me. Thanks.
