### ISSUE TITLE
react-native-scripts: Permission denied, exit status 126

### ISSUE THREAD

**Issue by napsta32** [Gozala/test-commonjs#15]
Error on clean install while trying to start a react-native empty app. I used these installation commands:
`npm install -g create-react-native-app`
`npm install -g react-native-cli`
`create-react-native-app test`
After, I run 
`cd test`
`npm start`
and received a bunch of errors.
```> test@0.1.0 start /media/data/test
> react-native-scripts start

sh: 1: react-native-scripts: Permission denied

npm ERR! Linux 4.10.0-42-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! test@0.1.0 start: `react-native-scripts start`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the test@0.1.0 start script 'react-native-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-native-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/data/test/npm-debug.log
```

Exit status 126 tells me that react-native-scripts isn't a valid command, however it doesn't have any sense because react-native-scripts was installed and exists inside node_modules. Can someone explain me what's happening?

**Comment by Gozala** [comment]
Hi @napsta32 I don't see how above output is related to this package. I am under impression it is not. If you could create reproducible example that uses this package and has an error coming from it, I might be able to help. Otherwise there's nothing I can do.

Closing this, but feel free to reopen if you create a reproducible example.
