### ISSUE TITLE
Wrong 'bugs' entry in package.json

### ISSUE THREAD

**Issue by giacecco** [Gozala/test-commonjs#4]
Trying to run: 

```
npm update outdated
```

on a little nodejs project I am working on I get a warning saying:

```
npm WARN test@0.4.1 package.json: bugs['web'] should probably be bugs['url']
```

It looks like the error is still there in the current code, if npm is right about package.json's synthax of course.

G.

**Comment by Gozala** [comment]
Yeah `npm` recently decided to rename `bugs.web` to `bugs.url`. Anyway just published 0.4.3 that should not have this warning.
